baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
theme: r-blog

publishDir: _public

# NOTE: we'd keep the static folder with the setting below, but the static content from the selected theme would so be added to the root!
#    
# module:
#   mounts:
#   - source: static
#     target: static/static

baseURL: # Hostname (and path) to the root, e.g. https://bep.is/

paginate: 8

permalinks:
    posts: /post/:slug/

taxonomies:
  tag: tags
  category: categories
  # you don't need to define the 2 basic taxonomies, but you'll need them if you want to add a 3rd one!

params:
    posts:
        page_size: 6 # custom paginator, if not defined, default is used
        featured:
            limit: 4 # -1 = all, 0 = none, 1..N - limit TOP
    taxonomy:
        categories:
            byCount: true

